# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stock_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10stock_data.proto\x12\tstockdata\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n\nStockPrice\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\x0c\n\x04high\x18\x02 \x01(\x01\x12\x0b\n\x03low\x18\x03 \x01(\x01\x12\r\n\x05\x63lose\x18\x04 \x01(\x01\"$\n\x08\x44ividend\x12\x18\n\x10\x61mount_per_share\x18\x01 \x01(\x01\",\n\nBonusShare\x12\x1e\n\x16shares_per_share_owned\x18\x01 \x01(\x01\"\xda\x01\n\x05\x45vent\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12.\n\nevent_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x0bstock_price\x18\x03 \x01(\x0b\x32\x15.stockdata.StockPriceH\x00\x12\'\n\x08\x64ividend\x18\x04 \x01(\x0b\x32\x13.stockdata.DividendH\x00\x12,\n\x0b\x62onus_share\x18\x05 \x01(\x0b\x32\x15.stockdata.BonusShareH\x00\x42\x0c\n\nevent_type\"3\n\x0f\x45ventCollection\x12 \n\x06\x65vents\x18\x01 \x03(\x0b\x32\x10.stockdata.Eventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKPRICE']._serialized_start=64
  _globals['_STOCKPRICE']._serialized_end=132
  _globals['_DIVIDEND']._serialized_start=134
  _globals['_DIVIDEND']._serialized_end=170
  _globals['_BONUSSHARE']._serialized_start=172
  _globals['_BONUSSHARE']._serialized_end=216
  _globals['_EVENT']._serialized_start=219
  _globals['_EVENT']._serialized_end=437
  _globals['_EVENTCOLLECTION']._serialized_start=439
  _globals['_EVENTCOLLECTION']._serialized_end=490
# @@protoc_insertion_point(module_scope)
