syntax = "proto3";

package stockdata;

import "google/protobuf/timestamp.proto";

message StockPrice {
  double open = 1;
  double high = 2;
  double low = 3;
  double close = 4;
}

message Dividend {
  double amount_per_share = 1;
}

message BonusShare {
  double shares_per_share_owned = 1;
}

message Event {
  string ticker = 1;
  google.protobuf.Timestamp event_date = 2;
  oneof event_type {
    StockPrice stock_price = 3;
    Dividend dividend = 4;
    BonusShare bonus_share = 5;
  }
}

message EventCollection {
  repeated Event events = 1;
}