// source: stock_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.stockdata.BonusShare', null, global);
goog.exportSymbol('proto.stockdata.Dividend', null, global);
goog.exportSymbol('proto.stockdata.Event', null, global);
goog.exportSymbol('proto.stockdata.Event.EventTypeCase', null, global);
goog.exportSymbol('proto.stockdata.EventCollection', null, global);
goog.exportSymbol('proto.stockdata.StockPrice', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stockdata.StockPrice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stockdata.StockPrice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stockdata.StockPrice.displayName = 'proto.stockdata.StockPrice';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stockdata.Dividend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stockdata.Dividend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stockdata.Dividend.displayName = 'proto.stockdata.Dividend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stockdata.BonusShare = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stockdata.BonusShare, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stockdata.BonusShare.displayName = 'proto.stockdata.BonusShare';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stockdata.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.stockdata.Event.oneofGroups_);
};
goog.inherits(proto.stockdata.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stockdata.Event.displayName = 'proto.stockdata.Event';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stockdata.EventCollection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.stockdata.EventCollection.repeatedFields_, null);
};
goog.inherits(proto.stockdata.EventCollection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stockdata.EventCollection.displayName = 'proto.stockdata.EventCollection';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stockdata.StockPrice.prototype.toObject = function(opt_includeInstance) {
  return proto.stockdata.StockPrice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stockdata.StockPrice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.StockPrice.toObject = function(includeInstance, msg) {
  var f, obj = {
open: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
high: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
low: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
close: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stockdata.StockPrice}
 */
proto.stockdata.StockPrice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stockdata.StockPrice;
  return proto.stockdata.StockPrice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stockdata.StockPrice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stockdata.StockPrice}
 */
proto.stockdata.StockPrice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOpen(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHigh(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLow(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClose(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stockdata.StockPrice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stockdata.StockPrice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stockdata.StockPrice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.StockPrice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpen();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getHigh();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getLow();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getClose();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional double open = 1;
 * @return {number}
 */
proto.stockdata.StockPrice.prototype.getOpen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.StockPrice} returns this
 */
proto.stockdata.StockPrice.prototype.setOpen = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double high = 2;
 * @return {number}
 */
proto.stockdata.StockPrice.prototype.getHigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.StockPrice} returns this
 */
proto.stockdata.StockPrice.prototype.setHigh = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double low = 3;
 * @return {number}
 */
proto.stockdata.StockPrice.prototype.getLow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.StockPrice} returns this
 */
proto.stockdata.StockPrice.prototype.setLow = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double close = 4;
 * @return {number}
 */
proto.stockdata.StockPrice.prototype.getClose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.StockPrice} returns this
 */
proto.stockdata.StockPrice.prototype.setClose = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stockdata.Dividend.prototype.toObject = function(opt_includeInstance) {
  return proto.stockdata.Dividend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stockdata.Dividend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.Dividend.toObject = function(includeInstance, msg) {
  var f, obj = {
amountPerShare: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stockdata.Dividend}
 */
proto.stockdata.Dividend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stockdata.Dividend;
  return proto.stockdata.Dividend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stockdata.Dividend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stockdata.Dividend}
 */
proto.stockdata.Dividend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmountPerShare(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stockdata.Dividend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stockdata.Dividend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stockdata.Dividend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.Dividend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAmountPerShare();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
};


/**
 * optional double amount_per_share = 1;
 * @return {number}
 */
proto.stockdata.Dividend.prototype.getAmountPerShare = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.Dividend} returns this
 */
proto.stockdata.Dividend.prototype.setAmountPerShare = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stockdata.BonusShare.prototype.toObject = function(opt_includeInstance) {
  return proto.stockdata.BonusShare.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stockdata.BonusShare} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.BonusShare.toObject = function(includeInstance, msg) {
  var f, obj = {
sharesPerShareOwned: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stockdata.BonusShare}
 */
proto.stockdata.BonusShare.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stockdata.BonusShare;
  return proto.stockdata.BonusShare.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stockdata.BonusShare} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stockdata.BonusShare}
 */
proto.stockdata.BonusShare.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSharesPerShareOwned(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stockdata.BonusShare.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stockdata.BonusShare.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stockdata.BonusShare} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.BonusShare.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSharesPerShareOwned();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
};


/**
 * optional double shares_per_share_owned = 1;
 * @return {number}
 */
proto.stockdata.BonusShare.prototype.getSharesPerShareOwned = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stockdata.BonusShare} returns this
 */
proto.stockdata.BonusShare.prototype.setSharesPerShareOwned = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.stockdata.Event.oneofGroups_ = [[3,4,5]];

/**
 * @enum {number}
 */
proto.stockdata.Event.EventTypeCase = {
  EVENT_TYPE_NOT_SET: 0,
  STOCK_PRICE: 3,
  DIVIDEND: 4,
  BONUS_SHARE: 5
};

/**
 * @return {proto.stockdata.Event.EventTypeCase}
 */
proto.stockdata.Event.prototype.getEventTypeCase = function() {
  return /** @type {proto.stockdata.Event.EventTypeCase} */(jspb.Message.computeOneofCase(this, proto.stockdata.Event.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stockdata.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.stockdata.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stockdata.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
eventDate: (f = msg.getEventDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
stockPrice: (f = msg.getStockPrice()) && proto.stockdata.StockPrice.toObject(includeInstance, f),
dividend: (f = msg.getDividend()) && proto.stockdata.Dividend.toObject(includeInstance, f),
bonusShare: (f = msg.getBonusShare()) && proto.stockdata.BonusShare.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stockdata.Event}
 */
proto.stockdata.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stockdata.Event;
  return proto.stockdata.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stockdata.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stockdata.Event}
 */
proto.stockdata.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventDate(value);
      break;
    case 3:
      var value = new proto.stockdata.StockPrice;
      reader.readMessage(value,proto.stockdata.StockPrice.deserializeBinaryFromReader);
      msg.setStockPrice(value);
      break;
    case 4:
      var value = new proto.stockdata.Dividend;
      reader.readMessage(value,proto.stockdata.Dividend.deserializeBinaryFromReader);
      msg.setDividend(value);
      break;
    case 5:
      var value = new proto.stockdata.BonusShare;
      reader.readMessage(value,proto.stockdata.BonusShare.deserializeBinaryFromReader);
      msg.setBonusShare(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stockdata.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stockdata.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stockdata.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEventDate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStockPrice();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.stockdata.StockPrice.serializeBinaryToWriter
    );
  }
  f = message.getDividend();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.stockdata.Dividend.serializeBinaryToWriter
    );
  }
  f = message.getBonusShare();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.stockdata.BonusShare.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ticker = 1;
 * @return {string}
 */
proto.stockdata.Event.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.stockdata.Event} returns this
 */
proto.stockdata.Event.prototype.setTicker = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp event_date = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.stockdata.Event.prototype.getEventDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.stockdata.Event} returns this
*/
proto.stockdata.Event.prototype.setEventDate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stockdata.Event} returns this
 */
proto.stockdata.Event.prototype.clearEventDate = function() {
  return this.setEventDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stockdata.Event.prototype.hasEventDate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional StockPrice stock_price = 3;
 * @return {?proto.stockdata.StockPrice}
 */
proto.stockdata.Event.prototype.getStockPrice = function() {
  return /** @type{?proto.stockdata.StockPrice} */ (
    jspb.Message.getWrapperField(this, proto.stockdata.StockPrice, 3));
};


/**
 * @param {?proto.stockdata.StockPrice|undefined} value
 * @return {!proto.stockdata.Event} returns this
*/
proto.stockdata.Event.prototype.setStockPrice = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.stockdata.Event.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stockdata.Event} returns this
 */
proto.stockdata.Event.prototype.clearStockPrice = function() {
  return this.setStockPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stockdata.Event.prototype.hasStockPrice = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Dividend dividend = 4;
 * @return {?proto.stockdata.Dividend}
 */
proto.stockdata.Event.prototype.getDividend = function() {
  return /** @type{?proto.stockdata.Dividend} */ (
    jspb.Message.getWrapperField(this, proto.stockdata.Dividend, 4));
};


/**
 * @param {?proto.stockdata.Dividend|undefined} value
 * @return {!proto.stockdata.Event} returns this
*/
proto.stockdata.Event.prototype.setDividend = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.stockdata.Event.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stockdata.Event} returns this
 */
proto.stockdata.Event.prototype.clearDividend = function() {
  return this.setDividend(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stockdata.Event.prototype.hasDividend = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional BonusShare bonus_share = 5;
 * @return {?proto.stockdata.BonusShare}
 */
proto.stockdata.Event.prototype.getBonusShare = function() {
  return /** @type{?proto.stockdata.BonusShare} */ (
    jspb.Message.getWrapperField(this, proto.stockdata.BonusShare, 5));
};


/**
 * @param {?proto.stockdata.BonusShare|undefined} value
 * @return {!proto.stockdata.Event} returns this
*/
proto.stockdata.Event.prototype.setBonusShare = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.stockdata.Event.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stockdata.Event} returns this
 */
proto.stockdata.Event.prototype.clearBonusShare = function() {
  return this.setBonusShare(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stockdata.Event.prototype.hasBonusShare = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.stockdata.EventCollection.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stockdata.EventCollection.prototype.toObject = function(opt_includeInstance) {
  return proto.stockdata.EventCollection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stockdata.EventCollection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.EventCollection.toObject = function(includeInstance, msg) {
  var f, obj = {
eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    proto.stockdata.Event.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stockdata.EventCollection}
 */
proto.stockdata.EventCollection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stockdata.EventCollection;
  return proto.stockdata.EventCollection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stockdata.EventCollection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stockdata.EventCollection}
 */
proto.stockdata.EventCollection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.stockdata.Event;
      reader.readMessage(value,proto.stockdata.Event.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stockdata.EventCollection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stockdata.EventCollection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stockdata.EventCollection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stockdata.EventCollection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.stockdata.Event.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Event events = 1;
 * @return {!Array<!proto.stockdata.Event>}
 */
proto.stockdata.EventCollection.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.stockdata.Event>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.stockdata.Event, 1));
};


/**
 * @param {!Array<!proto.stockdata.Event>} value
 * @return {!proto.stockdata.EventCollection} returns this
*/
proto.stockdata.EventCollection.prototype.setEventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.stockdata.Event=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stockdata.Event}
 */
proto.stockdata.EventCollection.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.stockdata.Event, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stockdata.EventCollection} returns this
 */
proto.stockdata.EventCollection.prototype.clearEventsList = function() {
  return this.setEventsList([]);
};


goog.object.extend(exports, proto.stockdata);
